@baseUrl = http://localhost:3000

# RECADOS
GET {{baseUrl}}/recados
?limit=10
&offset=0
# lista todos os recados

###

GET {{baseUrl}}/recados/32
# lista apenas um recado

###

POST {{baseUrl}}/recados
# cria um recado
Content-Type: application/json

{
  "recado": "Este é o recado que estou enviando.",
  "nova chave": "outro valor"
}

###

PATCH {{baseUrl}}/recados/2/
# atualiza um recado
Content-Type: application/json

{
  "recado": "Este é o recado que estou enviando.",
  "atualizar": true
}

###

DELETE {{baseUrl}}/recados/2/
# apaga um recado

### AppControllerGetHello

# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### ExemploDeRota

# @name ExemploDeRota
GET {{baseUrl}}/home/exemplo/

### ConceitosManualController Home

# @name Conceitos Manual ControllerHome
GET {{baseUrl}}/conceitos-manual/

### Conceitos AutomaticoController Home

# @name Conceitos AutomaticoControllerHome
GET {{baseUrl}}/conceitos-automatico/